services:
  
  ipfs-node:
    image: ipfs/kubo:latest
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./ipfs-data:/data/ipfs

  flux-sim:
    image: node:18
    working_dir: /app
    volumes:
      - ./flux-sim:/app
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"

