@echo off
echo 🛑 Stopping any running project-sentinel containers...
for /f "tokens=*" %%i in ('docker ps -q --filter "ancestor=project-sentinel"') do docker stop %%i

echo 🧹 Removing old containers...
for /f "tokens=*" %%i in ('docker ps -aq --filter "ancestor=project-sentinel"') do docker rm %%i

echo 🔨 Rebuilding project-sentinel image...
docker build -t project-sentinel .

echo 🚀 Starting fresh container on port 3000...
docker run -it --rm -p 3000:3000 project-sentinel
